(()=>{
const fmt=v=>{if(!v)return null;const d=new Date(v+'T12:00:00');return isNaN(d)?null:d},add=(d,n)=>{const x=new Date(d);x.setDate(x.getDate()+n);return x},days=(a,b)=>Math.max(0,Math.round((b-a)/86400000)),clamp=(n,a,b)=>Math.max(a,Math.min(b,n)),escG=v=>String(v||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function build(){if(document.querySelector('#ganttModal'))return;const m=document.createElement('div');m.id='ganttModal';m.className='gantt-modal';m.innerHTML='<div class="gantt-shell"><div class="gantt-head"><div><span class="gantt-kicker">PORTFEL PROJEKTÓW</span><h2>Wykres Gantta</h2><p>Projekty, postęp realizacji i terminy zadań na jednej osi czasu.</p></div><button class="gantt-close" id="ganttClose" type="button">×</button></div><div class="gantt-toolbar"><div class="gantt-legend"><span><i></i>Projekt / postęp</span><span><i class="task-line"></i>Termin zadania</span><span><i class="task-done"></i>Zadanie zakończone</span></div><div class="gantt-range" id="ganttRange"></div></div><div class="gantt-body" id="ganttBody"></div></div>';document.body.appendChild(m);document.querySelector('#ganttClose').onclick=closeG;m.onclick=e=>{if(e.target===m)closeG()}}
function range(){const ds=[new Date()];projects.forEach(p=>{const d=fmt(p.deadline);if(d)ds.push(d);(p.projectTasks||[]).forEach(t=>{const x=fmt(t.deadline);if(x)ds.push(x)})});let min=new Date(Math.min(...ds.map(d=>d.getTime()))),max=new Date(Math.max(...ds.map(d=>d.getTime())));min=add(min,-14);max=add(max,14);return{min,max,total:Math.max(1,days(min,max))}}
function months(r){const out=[];let c=new Date(r.min.getFullYear(),r.min.getMonth(),1,12);while(c<=r.max){const n=new Date(c.getFullYear(),c.getMonth()+1,1,12),s=c<r.min?r.min:c,e=n>r.max?r.max:n;out.push({l:clamp(days(r.min,s)/r.total*100,0,100),w:clamp(days(s,e)/r.total*100,1,100),t:c.toLocaleDateString('pl-PL',{month:'short',year:'numeric'}).replace('.','')});c=n}return out}
function projectStart(p,r){const ts=(p.projectTasks||[]).map(t=>fmt(t.deadline)).filter(Boolean);if(ts.length)return add(new Date(Math.min(...ts.map(d=>d.getTime()))),-7);return r.min}
function render(){build();const body=document.querySelector('#ganttBody');if(!projects.length){body.innerHTML='<div class="gantt-empty">Brak projektów.</div>';return}const r=range(),today=new Date();today.setHours(12,0,0,0);document.querySelector('#ganttRange').textContent=r.min.toLocaleDateString('pl-PL')+' — '+r.max.toLocaleDateString('pl-PL');const th=clamp(days(r.min,today)/r.total*100,0,100),mh=months(r).map(m=>'<div class="gantt-month" style="left:'+m.l+'%;width:'+m.w+'%">'+escG(m.t)+'</div>').join('');
const rows=projects.map(p=>{const ts=p.projectTasks||[],done=ts.filter(t=>t.done).length,prog=ts.length?Math.round(done/ts.length*100):(p.progress||0),end=fmt(p.deadline)||r.max,start=projectStart(p,r),l=clamp(days(r.min,start)/r.total*100,0,100),w=clamp(days(start,end)/r.total*100,1,100-l),taskCount=Math.max(1,ts.length);
const taskList=ts.length?'<div class="gantt-task-list">'+ts.map(t=>'<div class="gantt-task-info '+(t.done?'done':'')+'"><span>'+escG(t.text)+'</span><small>'+escG(t.deadline||'brak terminu')+'</small></div>').join('')+'</div>':'<div class="gantt-task-list empty"><div class="gantt-task-info"><span>Brak zadań</span></div></div>';
const taskLines=ts.map((t,i)=>{const d=fmt(t.deadline);if(!d)return'';const x=clamp(days(r.min,d)/r.total*100,0,100),lineStart=l,lineWidth=Math.max(.35,x-lineStart),top=50+i*18;return '<div class="gantt-task-line '+(t.done?'done':'')+'" style="top:'+top+'px;left:'+lineStart+'%;width:'+lineWidth+'%" title="'+escG(t.text)+' · termin '+escG(t.deadline||'brak')+'"><span></span></div><div class="gantt-task-end '+(t.done?'done':'')+'" style="top:'+(top-3)+'px;left:calc('+x+'% - 3px)" title="'+escG(t.text)+'"></div>'}).join('');
const rowH=72+Math.max(0,ts.length-1)*18;
return '<div class="gantt-row" style="--gantt-row-h:'+rowH+'px"><div class="gantt-project-info"><strong>'+escG(p.name)+'</strong><small>'+escG(p.owner||'Brak właściciela')+' · '+escG(statusText[p.status]||'—')+' · termin '+escG(p.deadline||'brak')+'</small><div class="gantt-progress-meta"><div class="gantt-progress-mini"><span style="width:'+prog+'%"></span></div><b>'+prog+'%</b><small>'+done+'/'+ts.length+' zadań</small></div>'+taskList+'</div><div class="gantt-track" style="min-height:'+rowH+'px"><div class="gantt-today" style="left:'+th+'%"></div><div class="gantt-bar" style="left:'+l+'%;width:'+w+'%"><div class="gantt-bar-fill" style="width:'+prog+'%"></div><div class="gantt-bar-label">'+escG(p.name)+'</div></div>'+taskLines+'</div></div>'}).join('');
body.innerHTML='<div class="gantt-table"><div class="gantt-months"><div class="gantt-left-head">PROJEKT / POSTĘP / ZADANIA</div><div class="gantt-month-grid">'+mh+'<div class="gantt-today" style="left:'+th+'%"></div></div></div>'+rows+'</div>'}
function openG(){render();document.querySelector('#ganttModal').classList.add('open');document.body.classList.add('gantt-open')}function closeG(){document.querySelector('#ganttModal')?.classList.remove('open');document.body.classList.remove('gantt-open')}
document.addEventListener('click',e=>{if(e.target.closest('#openGantt'))openG()});
})();